sudo: required
dist: Xenial

language: python

python:
    - "3.6"



#env:
#    - secure: "Hl7Mg82Li3e+rPRsll4dH1HgLvJKtJH2RASi/qX/lGsMALzsROJDYTJoTa2LHsFM46bbX+hp2zVCUs6o++S4sRTvOk50YnJUN0b3eqN/FmUbLs5ba7Y49QAoxbTduShTKxtmrkA3wizqTIS/TSCwrjtlt4Io/9PKz3g1Y+1SSDI="

branches:
    only:
    - develop-pelican
    - develop

cache:
    - pip

before_install:
    - sudo apt-get update
    - sudo apt-get install parallel graphviz

install:
    - sudo pip install pelican jinja2 py3babel babel beautifulsoup4 markdown six==1.10.0 jupyter
    - sudo locale-gen zh_CN.UTF-8
    - locale -a
    - pelican --version

script:
#    - git config --global user.email "$GIT_EMAIL"
#    - git config --global user.name "$GIT_NAME"
    - git config --global push.default simple
#    - git clone --depth 1 https://github.com/holbrook/pelican-plugins.git plugins
# copy plant uml
    - sudo mkdir -p /opt/plantuml
    - sudo cp lib/plantuml.jar /opt/plantuml
    - echo "#! /bin/sh" > plantuml
    - echo 'exec java -jar /opt/plantuml/plantuml.jar "$@"' >> plantuml
    - sudo install -m 755 -D plantuml /usr/bin/plantuml
    - plantuml -version

    - make publish

#after_success:
#   - cd output
#    - git add -A .
#    - git commit -m "update from travis" 
#    - git push --quiet
